config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  get 'password_resets/create'
  get 'password_resets/edit'
  get 'password_resets/update'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  root 'diaries#index'
  resources :diaries
  resources :users, only: %i[new create destroy] do
    member do
      get 'search'
    end
  end
  resource :profile, only: %i[show edit update]
  resources :password_resets, only: %i[new create edit update]

  resources :tags do
    get 'diaries', to: 'diaries#search'
  end
  get '/delete_account', to: 'profiles#delete'
  get '/terms', to: 'pages#terms'
  get '/privacy_policy', to: 'pages#privacy_policy'
  post 'like/:id', to: 'likes#create', as: 'create_like'
  post 'laugh/:id', to: 'laughs#create', as: 'create_laugh'
  post 'cry/:id', to: 'cries#create', as: 'create_cry'
  post 'surprise/:id', to: 'surprises#create', as: 'create_surprise'
  post 'paw/:id', to: 'paws#create', as: 'create_paw'
  get ':name', to: 'users#show'
end

app/models/diary.rb
class Diary < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :laughs, dependent: :destroy
  has_many :cries, dependent: :destroy
  has_many :surprises, dependent: :destroy
  has_many :paws, dependent: :destroy
  has_many :diary_tags, dependent: :destroy
  has_many :tags, through: :diary_tags

  validates :title, presence: true
  validates :story, presence: true

  def save_tag(sent_tags)
    exist_tags = tags.pluck(:tag_name) unless tags.nil?
    older_tags = exist_tags - sent_tags
    new_tags = sent_tags - exist_tags

    older_tags.each do |old|
      tags.delete Tag.find_by(tag_name: old)
    end

    new_tags.each do |new|
      new_diary_tag = Tag.find_or_create_by(tag_name: new)
      tags << new_diary_tag
    end
  end
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :set_diary, only: %i[edit update destroy]
  skip_before_action :require_login, only: %i[show index search]

  def index
    @diaries = Diary.includes(:user).page(params[:page]).order(created_at: :desc)
  end

  def new
    @diary = Diary.new
  end

  def create
    @diary = current_user.diaries.build(diary_params)
    tag_list = params[:diary][:tag_name].split(/[[:blank:]]/)
    if @diary.save
      @diary.save_tag(tag_list)
      redirect_to root_path, info: t('.success')
    else
      render :new
    end
  end

  def show
    @diary = Diary.find(params[:id])
  end

  def edit
    @tag_list = @diary.tags.pluck(:tag_name).join(' ')
  end

  def update
    @tag_list = params[:diary][:tag_name].split(/[[:blank:]]/)
    if @diary.update(diary_params)
      @diary.save_tag(@tag_list)
      redirect_to @diary, info: t('.success')
    else
      render :edit
    end
  end

  def destroy
    @diary.destroy!
    redirect_to diaries_path, info: t('.success')
  end

  def search
    @tag = Tag.find(params[:tag_id])
    @diaries = @tag.diaries.includes(:user).page(params[:page]).order(created_at: :desc)
  end

  private

  def set_diary
    @diary = current_user.diaries.find(params[:id])
  end

  def diary_params
    params.require(:diary).permit(:title, :story)
  end
end

app/views/diaries/_cry.html.slim
- if diary.cries.any?
  = link_to create_cry_path(diary), method: :post, remote: true, class: 'active-link' do
    i.fas.fa-tired.cried
  = diary.cries.count
- else
  = link_to create_cry_path(diary), method: :post, remote:true, class: 'active-link' do
    i.fas.fa-tired.not-reacted
  = diary.cries.count if diary.cries.any?

app/views/diaries/_diary.html.slim
.latest.d-flex.flex-column
  .avatar-icon
    = link_to "/#{diary.user.name}" do
      = image_tag diary.user.avatar, class: 'rounded-circle', size: '50x50'
  .latest-dream
    = link_to diary_path(diary), class: 'dream-link' do
      p.pr-3 「#{ diary.title }」
      p.ml-3.mr-3
        = diary.story.truncate(30)
    ul.index-reactions.d-flex.justify-content-center.mt-3
      = render 'diaries/reactions', diary: diary
    .tag-list.text-center
      - diary.tags.first(3).each do |tag|
        = link_to "##{tag.tag_name} ", tag_diaries_path(tag_id: tag.id), class: 'index-tags active-link mr-2'
      - if logged_in? && current_user.own?(diary)
        .index-twitter-icon.active-link.float-right
          = link_to "https://twitter.com/share?url=https://www.yume-book.com/diaries/#{diary.id}&text=今日こんなゆめ見ました%0a「#{ diary.title }」%0a&hashtags=夢,夢日記,YUMEBOOK", class: 'tweet-icon', target: '_blank' do
            i.fab.fa-twitter

app/views/diaries/_laugh.html.slim
- if diary.laughs.any?
  = link_to create_laugh_path(diary), method: :post, remote: true, class: 'active-link' do
    i.fas.fa-grin-squint-tears.laughed
  = diary.laughs.count
- else
  = link_to create_laugh_path(diary), method: :post, remote:true, class: 'active-link' do
    i.fas.fa-grin-squint-tears.not-reacted
  = diary.laughs.count if diary.laughs.any?

app/views/diaries/_like.html.slim
- if diary.likes.any?
  = link_to create_like_path(diary), method: :post, remote: true, class: 'active-link' do
    i.fas.fa-heart.liked
  = diary.likes.count
- else
  = link_to create_like_path(diary), method: :post, remote:true, class: 'active-link', id: 'test-like' do
    i.fas.fa-heart.not-reacted
  = diary.likes.count if diary.likes.any?

app/views/diaries/_paw.html.slim
- if diary.paws.any?
  = link_to create_paw_path(diary), method: :post, remote: true, class: 'active-link' do
    i.fas.fa-paw.pawed
  = diary.paws.count
- else
  = link_to create_paw_path(diary), method: :post, remote:true, class: 'active-link' do
    i.fas.fa-paw.not-reacted
  = diary.paws.count if diary.paws.any?

app/views/diaries/_reactions.html.slim
li.*{id: "like_#{diary.id}"}
  = render 'diaries/like', diary: diary
li.ml-3.*{id: "laugh_#{diary.id}"}
  = render 'diaries/laugh', diary: diary
li.ml-3.*{id: "cry_#{diary.id}"}
  = render 'diaries/cry', diary: diary
li.ml-3.*{id: "surprise_#{diary.id}"}
  = render 'diaries/surprise', diary: diary
li.ml-3.*{id: "paw_#{diary.id}"}
  = render 'diaries/paw', diary: diary

app/views/diaries/_surprise.html.slim
- if diary.surprises.any?
  = link_to create_surprise_path(diary), method: :post, remote: true, class: 'active-link' do
    i.fas.fa-flushed.surprised
  = diary.surprises.count
- else
  = link_to create_surprise_path(diary), method: :post, remote:true, class: 'active-link' do
    i.fas.fa-flushed.not-reacted
  = diary.surprises.count if diary.surprises.any?

app/views/diaries/edit.html.slim
- content_for(:title, @diary.title)
.container.mt-5
  .row-center
    .profile-field.col-lg-6.offset-lg-3.col-md-8.offset-md-2.col-sm-10.offset-sm-1.col-12.mt-3
      h1
        = @diary.title
      = render 'form', diary: @diary, tag_list: @tag_list
    .col-lg-6.offset-lg-3.col-md-8.offset-md-2.col-sm-10.offset-sm-1.col-12.mt-3
       = link_to diary_path(@diary) do
        .back.i.fas.fa-hand-point-left

app/views/diaries/index.html.slim
.container-fluid.mt-5
  .row.title-text
    .col-lg-6.offset-lg-3.col-md-8.offset-md-2.col-sm-12.col-12.mt-3.text-center
      h1.title-text.text-center
        span
          = t('.title')
.container
  .row
    .col-lg-6.offset-lg-3.col-md-8.offset-md-2.col-sm-11.offset-sm-1.col-11.offset-1.mt-3
      .post-button
        = link_to new_diary_path do
          i.fas.fa-pencil-alt
      .dreams-index
        - if @diaries.present?
          #dreams-paginame
            = render @diaries
        - else
          p.my-5.mr-3
            = t('.no_post')
    .col-lg-4.offset-lg-4.col-md-4.offset-md-4.col-sm-4.offset-sm-4.col-12.text-center.mt-3
      .active-link
        = link_to_next_page @diaries, t('.more_posts'), remote: true, class: 'more-dreams ml-5', id: 'more-dreams'

app/views/diaries/index.js.erb
$('#dreams-paginame').append("<%= escape_javascript(render 'diaries', object: @diaries) %>")
$("#more-dreams").replaceWith("<%= escape_javascript(link_to_next_page(@diaries, 'もっと見る', remote: true, class: 'more-dreams', id: 'more-dreams')
) %>");

app/views/diaries/new.html.slim
- content_for(:title, t('.title'))
.container.mt-5
  .row
    .profile-field.col-lg-6.offset-lg-3.col-md-8.offset-md-2.col-sm-10.offset-sm-1.col-10.offset-1.mt-3
      h1
        = t('.title_text')
      = render 'form', diary: @diary, tag_list: @tag_list

app/views/diaries/search.html.slim
- content_for(:title, "##{@tag.tag_name}")
.container.mt-4
  .row
    .col-lg-6.offset-lg-3.col-md-10.offset-md-1.col-sm-11.offset-sm-1.col-11.offset-1.mt-3
      .post-button
        = link_to new_diary_path do
          i.fas.fa-pencil-alt
      .dreams-index
        - if @diaries.present?
          #dreams-paginame
            .tagged-dreams
              | ##{@tag.tag_name}
            = render @diaries
        - else
          p.my-5.mr-3
            = t('.no_post')
    .col-lg-4.offset-lg-4.col-md-4.offset-md-4.col-sm-4.offset-sm-4.col-12.text-center.mt-3
      .active-link
        = link_to_next_page @diaries, t('.more_posts'), remote: true, class: 'more-dreams ml-5', id: 'more-dreams'

app/views/diaries/search.js.erb
$('#dreams-paginame').append("<%= escape_javascript(render @diaries) %>")
$("#more-dreams").replaceWith("<%= escape_javascript(link_to_next_page(@diaries, 'もっと見る', remote: true, class: 'more-dreams', id: 'more-dreams')
) %>");

app/views/diaries/show.html.slim
- content_for(:title, @diary.title)
.container
  .row
    .profile-field.col-lg-6.offset-lg-3.col-md-6.offset-md-3.col-sm-8.offset-sm-2.col-10.offset-1.mt-5
      - if logged_in? && current_user.own?(@diary)
        = render 'own_show', diary: @diary
      - else
        = link_to "/#{@diary.user.name}" do
          = image_tag @diary.user.avatar, class: 'avatar-icon rounded-circle mr15', size: '50x50'
        .dream-title.m-2
          = @diary.title
        .datetime.align-self-end.d-flex.justify-content-end
          = l @diary.created_at, format: :long
        table.table
          td= simple_format(@diary.story)
        .tag-list.ml-3
          - @diary.tags.each do |tag|
            = link_to "##{tag.tag_name} ", tag_diaries_path(tag_id: tag.id), class: 'tag-button active-link mr-2'
        ul.reactions.d-flex.justify-content-center
          = render 'reactions', diary: @diary