config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  get 'password_resets/create'
  get 'password_resets/edit'
  get 'password_resets/update'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  root 'diaries#index'
  resources :diaries
  resources :users, only: %i[new create destroy] do
    member do
      get 'search'
    end
  end
  resource :profile, only: %i[show edit update]
  resources :password_resets, only: %i[new create edit update]

  resources :tags do
    get 'diaries', to: 'diaries#search'
  end
  get '/delete_account', to: 'profiles#delete'
  get '/terms', to: 'pages#terms'
  get '/privacy_policy', to: 'pages#privacy_policy'
  post 'like/:id', to: 'likes#create', as: 'create_like'
  post 'laugh/:id', to: 'laughs#create', as: 'create_laugh'
  post 'cry/:id', to: 'cries#create', as: 'create_cry'
  post 'surprise/:id', to: 'surprises#create', as: 'create_surprise'
  post 'paw/:id', to: 'paws#create', as: 'create_paw'
  get ':name', to: 'users#show'
end

app/models/user.rb
class User < ApplicationRecord
  before_create :default_image
  authenticates_with_sorcery!

  has_one_attached :avatar
  has_many :diaries, dependent: :destroy

  enum role: { general: 0, admin: 1 }

  validates :name, presence: true, uniqueness: true, length: { maximum: 255 }
  validates :email, presence: true, uniqueness: true
  validates :password, confirmation: true, length: { minimum: 6 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :reset_password_token, uniqueness: true, allow_nil: true
  validates :terms_of_service, acceptance: true, on: :create

  def default_image
    unless avatar.attached?
      avatar.attach(io: File.open(Rails.root.join('app/assets/images/cloud.png')), filename: 'default-image.png', content_type: 'image/png')
    end
  end

  def own?(object)
    id == object.user_id
  end

  def self?(user)
    id == user.id
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login

  def show
    @user = User.find_by(name: params[:name])
    @diaries = @user.diaries.page(params[:page]).order(created_at: :desc)
    @diaries_on_calendar = @user.diaries.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      auto_login(@user)
      UserMailer.greeting_mail(@user).deliver_now
      redirect_to root_path, info: t('.success')
    else
      render :new
    end
  end

  def destroy
    @user = User.find(params[:id])
    UserMailer.account_deleted(@user).deliver_now
    @user.destroy!
    redirect_to root_path
  end

  def search
    @user = User.find(params[:id])
    @diaries = @user.diaries.where("DATE(created_at) = '#{params[:date]}'").order(created_at: :desc)
    @diaries_on_calendar = @user.diaries.all
    @date = params[:date].to_date
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :terms_of_service)
  end
end

app/views/users/_calendar.html.slim
.col-lg-4.offset-lg-4.col-md-6.offset-md-3.col-sm-8.offset-sm-3.col-11.offset-1.mt-5
  .calendar.p-3
    = month_calendar(attribute: :created_at, events: diaries) do |date, diaries|
      = link_to search_user_path(user, date: date) do
        - diaries.each do |diary|
        div class=("#{"date_with_diary" if diaries.present?}")
          = date.day

app/views/users/new.html.slim
- content_for(:title, t('.title'))
.container
  .row
    .profile-field.col-lg-6.offset-lg-3.col-md-8.offset-md-2.col-sm-10.offset-sm-1.col-10.offset-1.mt-5
      h1
        = t('.title')
      = form_with model: @user, local: true do |f|
        = render 'shared/error_messages', object: f.object
        .form-group
          = f.label :name
          = f.text_field :name, class: 'form-control'
        .form-group
          = f.label :email
          = f.text_field :email, class: 'form-control'
        .form-group
          = f.label :password, t('.password')
          = f.password_field :password, class: 'form-control'
        .form-group
          = f.label :password_confirmation
          = f.password_field :password_confirmation, class: 'form-control'
        .form-group.text-center
          = f.check_box :terms_of_service, id: 'test-terms'
          |
          = link_to '利用規約', terms_path, class: 'terms-of-service'
          | と
          = link_to 'プライバシーポリシー', privacy_policy_path, class: 'terms-of-service'
          | に同意する
        .actions.text-center
          = f.submit t('.submit'), class: 'active-link btn btn-info my-3'
      .d-flex.justify-content-around
        = link_to root_path, class: 'active-link' do
          .back.i.fas.fa-hand-point-left
        = link_to t('.to_login'), login_path, class: 'active-link mt-2'
      

app/views/users/search.html.slim
- content_for(:title, "#{@user.name}さんのページ")
.container.mt-4
  .row
    - if logged_in? && current_user.self?(@user)
      = render 'calendar', user: @user, diaries: @diaries_on_calendar
    .col-lg-6.offset-lg-3.col-md-10.offset-md-1.col-sm-11.offset-sm-1.col-11.offset-1.mt-3
      .post-button
        = link_to new_diary_path do
          i.fas.fa-pencil-alt
      .searched_date.text-center.m-4
        = l @date
        | のゆめ
      .dreams-index
        - if @diaries.present?
          #dreams-paginame
            = render @diaries
        - else
          p.my-5.mr-3
            = t('.no_post')

app/views/users/show.html.slim
- content_for(:title, "#{@user.name}さんのページ")
.container.mt-4
  .row
    .col-lg-6.offset-lg-3.col-md-10.offset-md-1.col-sm-11.offset-sm-1.col-11.offset-1.mt-3
      .dreams-index
        - if @diaries.present?
          #dreams-paginame
            = render 'diaries', diaries: @diaries
        - else
          p.my-5.mr-3
            = t('.no_post')
    .col-lg-4.offset-lg-4.col-md-4.offset-md-4.col-sm-4.offset-sm-4.col-12.text-center.mt-3
      .active-link
        = link_to_next_page @diaries, t('.more_posts'), remote: true, class: 'more-dreams ml-5', id: 'more-dreams'

app/views/users/show.js.erb
$('#dreams-paginame').append("<%= escape_javascript(render @diaries) %>")
$("#more-dreams").replaceWith("<%= escape_javascript(link_to_next_page(@diaries, 'もっと見る', remote: true, class: 'more-dreams', id: 'more-dreams')
) %>");