config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  get 'password_resets/create'
  get 'password_resets/edit'
  get 'password_resets/update'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  root 'diaries#index'
  resources :diaries
  resources :users, only: %i[new create destroy] do
    member do
      get 'search'
    end
  end
  resource :profile, only: %i[show edit update]
  resources :password_resets, only: %i[new create edit update]

  resources :tags do
    get 'diaries', to: 'diaries#search'
  end
  get '/delete_account', to: 'profiles#delete'
  get '/terms', to: 'pages#terms'
  get '/privacy_policy', to: 'pages#privacy_policy'
  post 'like/:id', to: 'likes#create', as: 'create_like'
  post 'laugh/:id', to: 'laughs#create', as: 'create_laugh'
  post 'cry/:id', to: 'cries#create', as: 'create_cry'
  post 'surprise/:id', to: 'surprises#create', as: 'create_surprise'
  post 'paw/:id', to: 'paws#create', as: 'create_paw'
  get ':name', to: 'users#show'
end

app/views/shared/_before_login_header.html.slim
header
  nav.navbar.navbar-expand.navigation.fixed-top style="flex-direction: column"
    = link_to t('defaults.app_title'), root_path, class: 'active-link navbar-brand'
    button.navbar-toggler aria-controls="navbarSupportedContent" aria-label=("Toggle navigation") data-target="#navbarSupportedContent"
      span.navbar-toggler-icon
    #navbarSupportedContent
      .navbar-nav.container-fluid.justify-content-end
        .nav-item.mr-5
          = link_to login_path, class: 'active-link' do
            i.fas.fa-sign-in-alt
            = t('defaults.login')
        .nav-item
          = link_to new_user_path, class: 'active-link' do
            i.fas.fa-user-plus
            = t('defaults.register')

app/views/shared/_error_messages.html.slim
- if object.errors.any?
  #error_messages.alert.alert-danger
    ul.mb-0.mr-0.pl-1
      - object.errors.full_messages.each do |message|
        li
          = message

app/views/shared/_flash_message.html.slim
- if flash.any?
  - flash.each do |type, msg|
    javascript:
      $(window).on("load", function() {
        toastr['#{type}']('#{msg}');
        })

app/views/shared/_footer.html.slim
.cushion
  footer.mt-5
    .d-flex.justify-content-around
        = link_to t('defaults.terms'), terms_path, class: 'active-link'
        = link_to t('defaults.privacy_policy'), privacy_policy_path, class: 'active-link'
    .active-link.text-center.mt-3
      = link_to t('defaults.inquiry'),
                'https://docs.google.com/forms/d/e/1FAIpQLSf2Ol_eN1Ek3JcLypvnZQ_0P5YR1gD4zmPs9es4t8g3O7RwYg/viewform?usp=sf_link',
         target: :_blank,
         rel: 'noopener noreferrer',
         class: 'active-link'
    .copyright.text-center.mt-3
      | Copyright © 2022 YUMEBOOK
    

app/views/shared/_google_tags.html.slim
/ google analytics
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-F5LCXR1G3J"></script>
  javascript:
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'G-F5LCXR1G3J');
/ google search console
meta name="google-site-verification" content="bORc3mV1OTuvtqW4Es_loEN80yfI4AnGSvOVCPPVLec"

app/views/shared/_loggedin_header.html.slim
header
  nav.navbar.navbar-expand.navigation.fixed-top style="flex-direction: column"
    = link_to t('defaults.app_title'), root_path, class: 'active-link navbar-brand'
    button.navbar-toggler aria-controls="navbarSupportedContent" aria-label=("Toggle navigation") data-target="#navbarSupportedContent"
      span.navbar-toggler-icon
    #navbarSupportedContent
      .navbar-nav.container-fluid.justify-content-end
        .nav-item.mr-3
          = link_to new_diary_path, class: 'nav-link active' do
            i.fas.fa-pencil-alt
            = t('defaults.new_post')
        .nav-item.mr-3
          - if controller.users_show? && current_user.self?(user)
            = link_to profile_path, class: 'nav-link active' do
              = image_tag current_user.avatar, class: 'avatar-icon rounded-circle mr15', size: '30x30'
              = t('defaults.profile')
          - else
            = link_to "/#{current_user.name}", class: 'nav-link active' do
              = image_tag current_user.avatar, class: 'avatar-icon rounded-circle mr15', size: '30x30'
              = t('defaults.my_posts')
        .nav-item
          = link_to logout_path, method: :delete, class: 'nav-link active' do
            i.fas.fa-sign-out-alt
            = t('defaults.logout')