config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  get 'password_resets/create'
  get 'password_resets/edit'
  get 'password_resets/update'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  root 'diaries#index'
  resources :diaries
  resources :users, only: %i[new create destroy] do
    member do
      get 'search'
    end
  end
  resource :profile, only: %i[show edit update]
  resources :password_resets, only: %i[new create edit update]

  resources :tags do
    get 'diaries', to: 'diaries#search'
  end
  get '/delete_account', to: 'profiles#delete'
  get '/terms', to: 'pages#terms'
  get '/privacy_policy', to: 'pages#privacy_policy'
  post 'like/:id', to: 'likes#create', as: 'create_like'
  post 'laugh/:id', to: 'laughs#create', as: 'create_laugh'
  post 'cry/:id', to: 'cries#create', as: 'create_cry'
  post 'surprise/:id', to: 'surprises#create', as: 'create_surprise'
  post 'paw/:id', to: 'paws#create', as: 'create_paw'
  get ':name', to: 'users#show'
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]
  def new; end

  def create
    @user = login(params[:email], params[:password])

    if @user
      redirect_back_or_to root_path, info: t('.success')
    else
      flash.now[:warning] = t('.fail')
      render :new
    end
  end

  def destroy
    @user = logout
    redirect_to root_path, info: t('.success')
  end
end

app/views/user_sessions/new.html.slim
- content_for(:title, t('.title'))
.container
  .row
    .profile-field.col-lg-6.offset-lg-3.col-md-8.offset-md-2.col-sm-10.offset-sm-1.col-10.offset-1.mt-5
      h1
        = t('.title')
      = form_with url: login_path, local: true do |f|
        .form-group
          = f.label :email, User.human_attribute_name(:email)
          = f.text_field :email, class: 'form-control'
        .form-group
          = f.label :password, User.human_attribute_name(:password)
          = f.password_field :password, class: 'form-control'
        .actions.text-center
          .active-link
            = link_to t('.password_forgot'), new_password_reset_path, class: 'active-link'
          = f.submit t('.submit'), class: 'active-link btn btn-info my-4'
      .d-flex.justify-content-around
        = link_to root_path, class: 'active-link' do
          .back.i.fas.fa-hand-point-left
        = link_to t('.to_register'), new_user_path, class: 'active-link'